#basic stuff

title: "Black Hole Article Summaries"
email: laurenchu8@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/bet.png'
favicon: ''
author: Lauren
paginate: 10
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 

# Authors
authors:
  lauren:
    name: Lauren
    display_name: Lauren Chu
    avatar: 'assets/images/IMG_4780.PNG'
    email: laurenchu8@gmail.com
    web: https://www.wowthemes.net/category/jekyll-themes/
    description: "Student from Hong Kong, studying in the UK. Grade 12"

# Social
social:
  instagram: 
  facebook: 
  twitter: 

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives